image: ubuntu/trusty

build:
  stage: build
  before_script:
    - rm -r gentoo
  script:
    - bash download.sh
    - bash download_misc.sh

build-via-git:
  stage: build
  before_script:
    - rm -r gentoo
  script:
    - bash download-via-git.sh
    - bash download_misc.sh

test:
  stage: test
  script:
    - mkdir test
    - bash install.sh test
