#!/sbin/runscript
# Copyright 1999-2002 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: /var/cvsroot/gentoo-x86/net-misc/dnsmasq/files/Attic/dnsmasq-init,v 1.2 2002/06/29 00:55:27 bangert dead $

depend() {
	need net
}

start() {
	ebegin "Starting dnsmasq"
	start-stop-daemon --start --quiet --exec /usr/sbin/dnsmasq \
		-- -x /var/run/dnsmasq.pid ${DNSMASQ_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping dnsmasq"
	start-stop-daemon --stop --quiet --pidfile /var/run/dnsmasq.pid
	eend $?
}
