#!/sbin/openrc-run

PIPEWIRE_RUNTIME_DIR="/run/pipewire"
DBUS_SESSION_BUS_ADDRESS="unix:path=/run/dbus/system_bus_socket"
name="pipewire automatic session manager"
description="On demand pipewire management"
command=/usr/bin/wireplumber
command_args="${wirplumber_args[@]}"
command_background=yes
pidfile="${PIPEWIRE_RUNTIME_DIR}/wireplumber.pid"

depend() {
  need dbus pipewire
}

start_pre() {
  export PIPEWIRE_RUNTIME_DIR
  export DBUS_SESSION_BUS_ADDRESS
}
